### ISSUE TITLE
Slotted fighter moveset mods doesn't seem to work so well in Squad Strike

### ISSUE THREAD

**Issue by DanielMC101** [Coolsonickirby/the_csk_collection_api#2]
So I'm using multiple moveset mods which are, Sandbag, Vegeta, Waluigi, Silver, Gogeta, and at first fighter, it works fine, but then when moving on to next slotted fighter, it just plays the base fighter, and it can even sometimes just get stuck after moving on to next fighter.
![01006a800016e000_2024-03-23_15-47-20-452](https://github.com/Coolsonickirby/the_csk_collection_api/assets/39068731/ac08e452-5873-45af-ab2a-0ca0227b79d1)
![01006a800016e000_2024-03-23_15-48-03-843](https://github.com/Coolsonickirby/the_csk_collection_api/assets/39068731/64c5d6d5-bd15-47c7-aeef-242dc0eacdb7)

**Comment by Coolsonickirby** [comment]
This is not an issue with the CSK Collection API, closing this issue.

**Comment by DanielMC101** [comment]
This is still happening btw, and turns out it even happens in world of light, just to clarify, it basically happens after moving onto the next fighter after dying, like it just loads up base fighter.

**Comment by DanielMC101** [comment]
@Coolsonickirby so what's the cause of this then if it's not csk collection issue?
